db_path          = 

web3_client      = "geth_clique"
web3_url         = 
web3_internaltx  = 

scan             = 
scan_start_block =  

bind             = 
solc_path        = 

[[named_address]]
name    = 
address = 
