# database ----------------------------------------

# where the database is located
db_path          = 

# true|false if we want to scan blocks and save it into db
scan             =  

# the starting block to start to retrieve blocks (only iff scan==true)
scan_start_block = 

# store with tx are contained in addr? (bool)
db_store_addr    = 

# store the transactions and receipts? (bool)
db_store_tx      = 

# store internal transactions? (bool)
db_store_itx     = 

# store list of last non empty blocks? (bool)
db_store_neb     = 

# web3 ----------------------------------------------

# web3 json-rpc port, e.g. http://localhost:8545
web3_client      = "geth_clique"
web3_url         = 

# process internal txs, true or false
# it requieres geth with --syncmode=full --gcmode=archive and --rpcapi debug 
web3_itx  = 

# compiler ------------------------------------------

# the path where solc binaries are stored (optional)
solc_path = 

# server --------------------------------------------

# http server binding (e.g. "0.0.0.0:8000")
bind         = 

# names ---------------------------------------------

# multiple named_address entries can be added to name accouts
[[named_address]]
# e.g. "me"
name =    
# e.g. "0x5d03df716ebf0e11bfb3e178fb39ed672c59ee61"
address = 
