db_path            = "data/db"
db_store_addr      = false
db_store_tx        = false
db_store_itx       = false
db_store_neb       = false

web3_url           = "http://my.ethchain.dnp.dappnode.eth:8545/"

scan               = false
scan_start_block   = 1

bind               = "0.0.0.0:80"
web3_client        = "geth"
web3_itx           = false
solc_bypass        = true